[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Kocha/vim-unite-tig'

[[plugins]]
repo = 'lambdalisue/vim-gita'
hook_add = """
  nnoremap <silent> [Space]gs :<C-u>Gita status<CR>
  nnoremap <silent> [Space]gc :<C-u>Gita commit<CR>
  nnoremap <silent> [Space]ga :<C-u>Gita commit --amend<CR>
  nnoremap <silent> [Space]gd :<C-u>call <SID>gita_tab('diff')<CR>
  nnoremap <silent> [Space]gb :<C-u>Gita browse<CR>
  nnoremap <silent> [Space]gl :<C-u>Gita blame<CR>

  let gita#features#commit#enable_default_mappings = 0

  function! s:gita_tab(cmd) abort
    if IsWindows()
      setlocal shellpipe=2>\&1\|iconv\ -f\ UTF-8\ -t\ CP932>%s
    endif
    execute 'tabedit ' . expand('%')
    execute 'Gita ' . a:cmd
    if IsWindows()
      setlocal shellpipe&
    endif
  endfunction
"""

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'Shougo/unite-sudo'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/autofmt'

