[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Kocha/vim-unite-tig'

[[plugins]]
repo = 'lambdalisue/vim-gita'
hook_add = """
  let g:gita#suppress_warning = 1

  nnoremap <silent> [Space]gs :<C-u>Gita status<CR>
  nnoremap <silent> [Space]gc :<C-u>Gita commit<CR>
  nnoremap <silent> [Space]ga :<C-u>Gita commit --amend<CR>
  nnoremap <silent> [Space]gd :<C-u>call <SID>gita_tab('diff')<CR>
  nnoremap <silent> [Space]gb :<C-u>Gita browse<CR>
  nnoremap <silent> [Space]gl :<C-u>Gita blame<CR>

  autocmd FileType gita-status
  \ nmap <buffer> cc <Plug>(gita-commit-open)
  autocmd FileType gita-status
  \ nmap <buffer> cA <Plug>(gita-commit-open-amend)

  function! s:gita_tab(cmd) abort
    if IsWindows()
      setlocal shellpipe=2>\&1\|iconv\ -f\ UTF-8\ -t\ CP932>%s
    endif
    execute 'tabedit ' . expand('%')
    execute 'Gita ' . a:cmd
    if IsWindows()
      setlocal shellpipe&
    endif
  endfunction
"""

# [[plugins]]
# repo = 'lambdalisue/gina.vim'
# hook_add = """
#   nnoremap <silent> [Space]gs :<C-u>Gina status<CR>
#   nnoremap <silent> [Space]gc :<C-u>Gina commit<CR>
#   nnoremap <silent> [Space]ga :<C-u>Gina commit --amend<CR>
#   nnoremap <silent> [Space]gd :<C-u>call <SID>gina_tab('diff')<CR>
#   nnoremap <silent> [Space]gb :<C-u>Gina browse<CR>
#   nnoremap <silent> [Space]gl :<C-u>Gina browse --scheme=blame<CR>
# 
#   function! s:gina_tab(cmd) abort
#     if IsWindows()
#       setlocal shellpipe=2>\&1\|iconv\ -f\ UTF-8\ -t\ CP932>%s
#     endif
#     execute 'tabedit ' . expand('%')
#     execute 'Gina ' . a:cmd
#     if IsWindows()
#       setlocal shellpipe&
#     endif
#   endfunction
# """

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'Shougo/unite-sudo'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

