[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = """
  nnoremap <silent> [Space]gs :<C-u>Gina status<CR>
  nnoremap <silent> [Space]gc :<C-u>Gina commit<CR>
  nnoremap <silent> [Space]ga :<C-u>Gina commit --amend<CR>
  nnoremap <silent> [Space]gd :<C-u>call <SID>gina_tab('diff')<CR>
  nnoremap <silent> [Space]gb :<C-u>Gina browse<CR>
  nnoremap <silent> [Space]gl :<C-u>Gina browse --scheme=blame<CR>

  function! s:gina_tab(cmd) abort
    if IsWindows()
      setlocal shellpipe=2>\&1\|iconv\ -f\ UTF-8\ -t\ CP932>%s
    endif
    execute 'tabedit ' . expand('%')
    execute 'Gina ' . a:cmd
    if IsWindows()
      setlocal shellpipe&
    endif
  endfunction
"""

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "has('python3') && !has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "has('python3') && !has('nvim')"

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

